Cora:
  dataset: Cora
  lr: 0.01
  wd: 5e-4
  layer_num: 2
  hidden: 32
  lam_loss: 4.6
  p1: 0.1
  p2: 0.7
  tem: 0.5
  lam: 1.0
  dropnode_rate: 0.5
  input_droprate: 0.5
  hidden_droprate: 0.5
  sample: 4
  use_bn: False
  node_norm: False
  clip_norm: -1
  order: 8
  pseudo_warmup: 25
  after_dropnode_rate: 0.3
  after_lr: 0.01
  after_wd: 0.0005
  patience: 200
  warmup: 400
Citeseer:
  dataset: Citeseer
  lr: 0.01
  wd: 5e-4
  layer_num: 2
  hidden: 32
  lam_loss: 0.7
  p1: 0.35
  p2: 0.9
  tem: 0.3
  lam: 0.7
  dropnode_rate: 0.5
  input_droprate: 0.0
  hidden_droprate: 0.2
  sample: 2
  use_bn: False
  node_norm: False
  clip_norm: -1
  order: 2
  pseudo_warmup: 21
  after_dropnode_rate: 0.5
  after_lr: 0.01
  after_wd: 0.0005
  patience: 200
  warmup: 400
Pubmed:
  dataset: Pubmed
  lr: 0.01
  wd: 0.01
  layer_num: 1
  hidden: 64
  lam_loss: 3.9
  p1: 0.03
  p2: 0.77
  tem: 0.5
  lam: 1.6
  dropnode_rate: 0.5
  input_droprate: 0.3
  hidden_droprate: 0.2
  sample: 2
  use_bn: True
  node_norm: False
  clip_norm: 0.1
  order: 5
  pseudo_warmup: 18
  after_dropnode_rate: 0.35
  after_lr: 0.1
  after_wd: 0.005
  warmup: 200
  patience: 200
Computers:
  dataset: Computers
  lr: 0.01
  wd: 0.0005
  layer_num: 2
  hidden: 64
  lam_loss: 2.1
  p1: 0.05
  p2: 0.7
  tem: 0.8
  lam: 1.1
  dropnode_rate: 0.1
  input_droprate: 0.1
  hidden_droprate: 0.9
  sample: 2
  use_bn: True
  node_norm: True
  clip_norm: 0.1
  order: 2
  pseudo_warmup: 13
  after_dropnode_rate: 0.6
  after_lr: 0.01
  after_wd: 0.0005
  warmup: 50
  patience: 100
CS:
  dataset: CS
  lr: 0.01
  wd: 0.0005
  layer_num: 1
  hidden: 64
  lam_loss: 3.6
  p1: 0.05
  p2: 0.5
  tem: 0.4
  lam: 1.3
  dropnode_rate: 0.1
  input_droprate: 0.8
  hidden_droprate: 0.6
  sample: 3
  use_bn: True
  node_norm: True
  clip_norm: 0.1
  order: 2
  pseudo_warmup: 32
  after_dropnode_rate: 0.1
  after_lr: 0.01
  after_wd: 0.0005
  warmup: 160
  patience: 100
Corafull:
  dataset: Corafull
  lr: 0.01
  wd: 0.0005
  layer_num: 1
  hidden: 64
  lam_loss: 1.7
  p1: 0.2
  p2: 0.7
  tem: 0.3
  lam: 1.2
  dropnode_rate: 0.1
  input_droprate: 0.7
  hidden_droprate: 0.8
  sample: 2
  use_bn: True
  node_norm: False
  clip_norm: 0.1
  order: 3
  pseudo_warmup: 37
  after_dropnode_rate: 0.1
  after_lr: 0.01
  after_wd: 0.0005
  warmup: 90
  patience: 100